# Change these first
owner: KomeStudio # Your GitHub organization or username, where this repository lives
repo: Status # The name of this repository

sites:
  - name: Kome Studio
    url: https://komestudio.com
  - name: Kami Machine
    url: https://kamimachine.com
  - name: Kome Smart
    url: https://kome.top
  - name: Github Hoangdacviet
    url: http://hoangdacviet.github.io
  - name: Secret Site
    url: $https://kami.vn

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.komestudio.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/KomeStudio/Status/master/KomeD.png
  name: Kome Studio Status
  favicon: https://raw.githubusercontent.com/KomeStudio/Status/master/KomeD.png
  # faviconSvg: https://example.com/logo.svg
  introTitle: "Kome Studio 🚀 KomeVerse 😊 Play Smile Belong"
  introMessage: Status page **real-time** data from our komestudio.com No server required
  navbar:
    - title: LinkedIn
      href: https://www.linkedin.com/company/komestudio
    - title: TikTok
      href: https://tiktok.com/@komestudios
    - title: YouTube
      href: https://youtube.com/@komestudios
    - title: Facebook
      href: https://facebook.com/komestudios

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
